# Generated by Django 4.1.4 on 2022-12-20 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_studentteachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='students', through='school.StudentTeachers', to='school.teacher'),
        ),
        migrations.AlterField(
            model_name='studentteachers',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='through', to='school.student'),
        ),
        migrations.AlterField(
            model_name='studentteachers',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='through', to='school.teacher'),
        ),
    ]
